### ISSUE TITLE
iOS 8.4 bug (drawer hidden)

### ISSUE THREAD

**Issue by yjukaku** [bramus/ion-drawer-vertical#11]
First, thanks for this project! It's really great.

There seems to be an issue on iOS 8 where the drawer content is hidden.  Hovering over the element in the Safari inspector shows the blue content "shadow" in the right place, but the item isn't visible at all.  Upon further inspection it looks like `position: fixed` might be causing an issue?

Any ideas on how to fix this?

**Comment by jariwalabhavesh** [comment]
+1 same issue

**Comment by bramus** [comment]
@yjukaku Could you try playing around with the value for `z-index`?

Also, are you using the latest version? This issue was/should've been fixed with version 1.7.0 (see 791e9fcc5895ec0362909a64a7e8ad2e001af177)

**Comment by yjukaku** [comment]
This was obviously a while back, but I do seem to remember that z-index was not helping, no matter what I set it to.

**Comment by jariwalabhavesh** [comment]
Actually facing same issue with in ios and in android it was working, reason in ios was, drawer css was effected by some other media queries in code so i shifted ion-drawer css above that custom css and it start working in ios.

**Comment by bramus** [comment]
OK. I'll be closing this issue for now as it cannot be reproduced at this time / most likely is some other CSS that creates a conflict. Feel free to reopen if it should occur again.
