### ISSUE TITLE
Showing drawer content partly when closed

### ISSUE THREAD

**Issue by BluesyBlue** [bramus/ion-drawer-vertical#12]
Fantastic plugin! I implemented it to my app and it works great. However, I wanted to modify the way it works so that the wrapper is actually showing (let's say 20%) from the bottom of the screen. I managed to do this by editing one single CSS style:

ion-drawer-vertical-wrapper.up.closed { bottom: 20%; }

It works, but it breaks the animation and position calculations. When toggling / dragging, it jumps that 20% off and also goes over the screen boundaries. Any help would be appreciated on how to modify it so that it would be as smooth moving as by default? I am not sure how to go about altering the plugin js calculations. Cheers!

**Comment by bramus** [comment]
With the merging of #7 this can be done now.
