### ISSUE TITLE
Inject dependencies by string to be able to minify the code

### ISSUE THREAD

**Issue by sebthieti** [bramus/ion-drawer-vertical#20]
As of now, dependencies needed by ionDrawerVertical are not injected as string, but only by parameter name. Because of that, once minified, the library won't work, as new minified parameters names won't mean anything to angular.

You should change this:
`.controller('$ionDrawerVertical', function($scope, $element, $attrs ...`

To this:
`.controller('$ionDrawerVertical', ['$scope', '$element', '$attrs', function($scope, $element, $attrs ...`

I've made a PR for that #21

**Comment by bramus** [comment]
Fixed in #21
